@startuml
'https://plantuml.com/class-diagram

class Topic{

}

interface Receive{
    +void printNew()
    +void updateNew()
}
class MemberA
class MemberB

Topic <----o Receive:members
Receive ...|> MemberA
Receive ...|> MemberB
Topic ---> MemberB:topic
Topic ---> MemberA:topic
@enduml