@startuml
'https://plantuml.com/class-diagram

abstract GiaiThuong{
- boSoTrungThuong: List<String>
- tenGiai: String
- giaiThapHon: VeSo
+ giaiThapHon(GiaiThuong v): GiaiThuong
+ doVeSo(String veSo): String
}

GiaiThuong <|--- GiaiBinhThuong
GiaiThuong <|--- GiaiThapNhap
GiaiThuong <--- GiaiBinhThuong:"giaThapHon"
GiaiThuong <|--- GiaiKK

note bottom of GiaiKK
   Đặt sau giải đặt biệt
end note
@enduml